from .prompts import (
    SYSTEM_MESSAGE,
    SYSTEM_MESSAGE_DOC,
    TASK1_CALL_CHAIN_TEMPLATE,
    TASK2_MODULE_DIAGRAM_TEMPLATE,
    TASK2_TEXT_TABLE_TEMPLATE,
    TASK3_CONTROL_FLOW_TEMPLATE,
)

__all__ = [
    "SYSTEM_MESSAGE",
    "SYSTEM_MESSAGE_DOC",
    "TASK1_CALL_CHAIN_TEMPLATE",
    "TASK2_MODULE_DIAGRAM_TEMPLATE",
    "TASK2_TEXT_TABLE_TEMPLATE",
    "TASK3_CONTROL_FLOW_TEMPLATE",
]


